### ISSUE TITLE
[a25] Map 28 - Market has no health triggers errors

### ISSUE THREAD

**Issue by LangLangBart** [SciGuy42/Macedonia_0ad#5]
### issue
The entity `uid="7131"` on the 28th map has no health in its template file, its capture will trigger errors.

### to reproduce
* start the 28th map
* find the market in the north-east (more east then north) from `Apa Saka`
* select it and type `wololo`
* see errors&image below for more clarity
```zsh
ERROR: JavaScript error: maps/scenarios/Macedonia_28.js line 244
health_u is null
  Trigger.prototype.OwnershipChangedAction@maps/scenarios/Macedonia_28.js:244:3
  Trigger.prototype.DoAction@simulation/components/Trigger.js:371:19
  Trigger.prototype.CallEvent@simulation/components/Trigger.js:332:9
  Trigger.prototype.OnGlobalOwnershipChanged@simulation/components/Trigger.js:259:7
  Cheat@simulation/helpers/Cheat.js:42:18
  cheat@simulation/helpers/Commands.js:72:8
  ProcessCommand@simulation/helpers/Commands.js:53:23
ERROR: Script message handler OnGlobalOwnershipChanged failed
```
<img src="https://ttm.sh/wu9.jpg" width="600">

### possible solution(s)
1. use a different template or
```diff
--- a/maps/scenarios/Macedonia_28 - Alexandria Eschate.xml	
+++ b/maps/scenarios/Macedonia_28 - Alexandria Eschate.xml	
 			<Actor seed="4623"/>
 		</Entity>
 		<Entity uid="7131">
-			<Template>structures/trading_post_desert</Template>
+			<Template>structures/pers/market</Template>
 			<Player>5</Player>
 			<Position x="1945.8423" z="1316.271"/>
 			<Orientation y="2.64074"/>
```
2. `Engine.DestroyEntity()`
```diff
--- a/maps/scenarios/Macedonia_28.js
+++ b/maps/scenarios/Macedonia_28.js
 	//if structure captured, it gets destroyed
 	if ((data.from == 2 || data.from == 5 || data.from == 4) && data.to == 1)
 	{
 		let health_u = Engine.QueryInterface(data.entity, IID_Health);
-		health_u.Kill();
-		
+		if (health_u)
+			health_u.Kill();
+		else
+			Engine.DestroyEntity(data.entity);
 	}
 };
 
```

### additonal notes
Maps that contain a similar function upon on `OwnershipChangedAction`.
* [Macedonia_23.js](../blob/a25/maps/scenarios/Macedonia_23.js)
* [Macedonia_26.js](../blob/a25/maps/scenarios/Macedonia_26.js)
* [Macedonia_27.js](../blob/a25/maps/scenarios/Macedonia_27.js)

**Comment by SciGuy42** [comment]
Thanks for catching this! I have updated the code for 27 and 28 (in the other two, there are no markets that can be captured to trigger this issue)

**Comment by LangLangBart** [comment]
The errors can no longer be reproduced, I am closing the issue now.

**Comment by LangLangBart** [comment]
Commit: 00f1826
