### ISSUE TITLE
[Crash] Macedonia_5 - Magnesia

### ISSUE THREAD

**Issue by LangLangBart** [SciGuy42/Macedonia_0ad#8]
### Description

- start the map `Macedonia_5 - Magnesia`, zoom around a bit and the map crashes 
- the problem was reported in the [forum](https://wildfiregames.com/forum/topic/92593-game-crashes-when-it-cannot-find-a-terrain/#comment-519213), it has to do with a `fancy` grass - `grass1_spring_fancy`
- a [python script](https://code.wildfiregames.com/P268) is available to fix the problem
  - see related issue: https://github.com/0ad-matters/community-maps-2/issues/47

#### possible solution

```sh
# download `python` script
curl -o FancyGrassRemover.py https://code.wildfiregames.com/file/data/ffws7ssbs7rmtxynhhpz/PHID-FILE-qdc3bq7ai2fo6gswm7cf/FancyGrassRemover

# run it
python FancyGrassRemover.py
# INFO - Found 45 file(s).
# INFO - Patching ./maps/scenarios/Macedonia_2.pmp...
# INFO - Patching ./maps/scenarios/Macedonia_5 - Magnesia.pmp...

# Issue solved
```

---

- created the issue in order not to forget to fix it

**Comment by StanleySweet** [comment]
LGTM can you make another PR?
